### ISSUE TITLE
Asserting inside a Handler

### ISSUE THREAD

**Issue by tipsy** [javalin/javalin-test#6]
I'm not sure if you saw the issue about assering in Handlers @oharaandrew314; https://github.com/tipsy/javalin/issues/813

Do you have any thoughts on this?

**Comment by oharaandrew314** [comment]
Sounds like he should be using https://github.com/PawelAdamski/HttpClientMock instead.

**Comment by oharaandrew314** [comment]
So, If I understand his needs correctly, he wants to mock out an external API using an embedded javalin server.  One might hope that putting a failing assertion inside the javalin request handler would cascade back to the test caller and fail the test.  Of couse, this won't work because the test and the server are seperated by an HTTP call.

I don't think javalin or javalin-test could or should support this kind of thing.  If you wants assertions to fail tests, you should mock the client instead of the server.

**Comment by oharaandrew314** [comment]
Closing because upstream issue is closed
